// Contract-conformance (the split-brain guard): the model calls tools the SERVER
// advertises, but the CLIENT registry executes them. This test asserts the two agree,
// using the bundled catalog (regenerated by `npm run codegen`). A tool added / removed /
// renamed in the backend contract without a matching client change fails here.
import { describe, expect, it } from "vitest";

import { createToolRegistry } from "../tools";
import { requiredParams, snapshotToolNames, toolParams } from "./params";
import { toolNames } from "./views";
import { WITHDRAWN_TOOLS } from "./withdrawn";

// Registered client-side but INTENTIONALLY not advertised to the model
// (gateway<->client internals). Empty now that read_media is unregistered; the
// hook stays for any future internal-only registry entry.
const CLIENT_INTERNAL: readonly string[] = [];
// Advertised in the contract but executed SERVER-side (not client-registered).
// Empty today — every artdaddy tool runs client-side.
const SERVER_ONLY: readonly string[] = [];
// Implemented here but withdrawn from the catalog on purpose.
const UNADVERTISED = [...CLIENT_INTERNAL, ...WITHDRAWN_TOOLS];

describe("contract conformance", () => {
  const registered = createToolRegistry(() => null).names();
  const contract = toolNames();
  const clientFacing = registered.filter((n) => !UNADVERTISED.includes(n));

  it("no phantom local tools: every client tool (minus internals) is in the contract", () => {
    expect(clientFacing.filter((n) => !contract.includes(n))).toEqual([]);
  });

  it("no missing handlers: every contract tool is client-registered (or server-only)", () => {
    const has = new Set([...registered, ...SERVER_ONLY]);
    expect(contract.filter((n) => !has.has(n))).toEqual([]);
  });

  it("registry and contract are the same set (regenerate the catalog with `npm run codegen`)", () => {
    expect([...new Set([...clientFacing, ...SERVER_ONLY])].sort()).toEqual([...contract].sort());
  });

  it("declared internals are actually registered (keeps the allowlist honest)", () => {
    for (const n of CLIENT_INTERNAL) expect(registered).toContain(n);
  });

  // Both directions, because each catches a different mistake. A name that is no longer
  // registered, or that the catalog offers again, makes the list a lie; and a tool withdrawn
  // server-side that nobody acknowledged here is indistinguishable from real drift.
  it("every withdrawn tool is still implemented and really is unadvertised", () => {
    for (const n of WITHDRAWN_TOOLS) {
      expect(registered, `${n} is listed as withdrawn but no longer implemented`).toContain(n);
      expect(contract, `${n} is listed as withdrawn but the catalog offers it`).not.toContain(n);
    }
  });

  it("no tool is withdrawn without being acknowledged", () => {
    const unacknowledged = registered
      .filter((n) => !contract.includes(n) && !UNADVERTISED.includes(n))
      .sort();
    expect(unacknowledged, "withdrawn server-side; add to WITHDRAWN_TOOLS or restore").toEqual([]);
  });
});

describe("param conformance", () => {
  const registered = createToolRegistry(() => null).names();
  const snapNames = snapshotToolNames();

  it("every registered client tool has a param entry", () => {
    expect(registered.filter((n) => !UNADVERTISED.includes(n) && !snapNames.includes(n))).toEqual(
      [],
    );
  });

  // There was a test here asserting the param set equals the contract set. Both now derive from
  // the one bundled catalog, so it could not fail; the guard it stood for (client catalog vs the
  // server's registry) lives in the server repo, which can see both.

  it("every required param is also a declared param", () => {
    for (const n of snapNames) {
      const params = new Set(toolParams(n));
      expect(
        requiredParams(n).filter((r) => !params.has(r)),
        n,
      ).toEqual([]);
    }
  });
});
