// Dev-only parity probe: composite the shared parity timeline via WebGL, read
// the pixels back, and diff against the ffmpeg-rendered reference (generated by
// smoke.e2e into public/parity-ref.png). Reports mean/max per-channel diff.
// Structural parity (crop/flip/fit/layout/opacity/position) shows as a low mean;
// interpolation differences (WebGL bilinear vs ffmpeg bicubic) show at edges as
// a higher max. Not part of the production build.
import { PARITY_PROBE_TIME, parityTimeline } from "./__parity";
import { loadImage } from "./loader";
import { PreviewRenderer } from "./renderer";
import { type AssetDims, buildScene } from "./scene";

const out = document.getElementById("out") as HTMLCanvasElement;
const refCanvas = document.getElementById("ref") as HTMLCanvasElement;
const diffCanvas = document.getElementById("diff") as HTMLCanvasElement;
const status = document.getElementById("status");
const set = (v: string): void => {
  (window as unknown as { __probe: string }).__probe = v;
  if (status) status.textContent = v;
};

void (async () => {
  try {
    const renderer = new PreviewRenderer(out);
    const fg = await loadImage("/parity-fg.png");
    renderer.setTexture("/parity-fg.png", fg.bitmap);
    const dims = new Map<string, AssetDims>([["/parity-fg.png", fg.dims]]);
    renderer.render(buildScene(parityTimeline("/parity-fg.png"), PARITY_PROBE_TIME, dims));
    const px = renderer.readPixels(); // bottom-up RGBA

    const ref = await loadImage("/parity-ref.png");
    refCanvas.width = px.width;
    refCanvas.height = px.height;
    const rctx = refCanvas.getContext("2d") as CanvasRenderingContext2D;
    rctx.drawImage(ref.bitmap, 0, 0, px.width, px.height);
    const refData = rctx.getImageData(0, 0, px.width, px.height).data; // top-down

    let sum = 0;
    let max = 0;
    let n = 0;
    const dctx = diffCanvas.getContext("2d") as CanvasRenderingContext2D;
    diffCanvas.width = px.width;
    diffCanvas.height = px.height;
    const viz = dctx.createImageData(px.width, px.height);
    for (let y = 0; y < px.height; y++) {
      for (let x = 0; x < px.width; x++) {
        const gi = ((px.height - 1 - y) * px.width + x) * 4; // flip WebGL rows to top-down
        const ri = (y * px.width + x) * 4;
        let pd = 0;
        for (let c = 0; c < 3; c++) {
          const d = Math.abs(px.data[gi + c] - refData[ri + c]);
          sum += d;
          if (d > max) max = d;
          pd += d;
          n += 1;
        }
        const oi = (y * px.width + x) * 4;
        const amp = Math.min(255, pd * 2); // amplify to make small diffs visible
        viz.data[oi] = amp;
        viz.data[oi + 1] = amp;
        viz.data[oi + 2] = amp;
        viz.data[oi + 3] = 255;
      }
    }
    dctx.putImageData(viz, 0, 0);
    const mean = sum / n;
    // Mean is the structural-parity metric; max is dominated by edge interpolation.
    const ok = mean < 10;
    set(`${ok ? "ok" : "FAIL"} meanDiff=${mean.toFixed(2)} maxDiff=${max}`);
  } catch (e) {
    set(`error: ${String(e)}`);
  }
})();
