// Regenerate src/timeline/fontMetrics.data.ts from the fonts the app ships (src-tauri/resources/fonts).
//
//   npm run fontmetrics
//
// The table is what lets the export size text the way the preview does and lets add_captions know
// how wide a caption draws, without parsing a font at run time. fontMetrics.conformance.test.ts
// fails whenever a font file and the committed table disagree, so a changed font cannot ship with
// stale numbers.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import { parseFont } from "../src/timeline/fontParse";

const root = path.resolve(import.meta.dirname, "..");
const fontsDir = path.join(root, "src-tauri", "resources", "fonts");
const outFile = path.join(root, "src", "timeline", "fontMetrics.data.ts");

const faces: Record<string, unknown> = {};
for (const file of readdirSync(fontsDir)
  .filter((f) => /\.(ttf|otf)$/i.test(f))
  .sort()) {
  const font = parseFont(new Uint8Array(readFileSync(path.join(fontsDir, file))));
  const cps = [...font.advances.keys()].sort((a, b) => a - b);
  const ranges: Array<[number, number[]]> = [];
  for (const cp of cps) {
    const last = ranges[ranges.length - 1];
    const adv = font.advances.get(cp)!;
    if (last && last[0] + last[1].length === cp) last[1].push(adv);
    else ranges.push([cp, [adv]]);
  }
  faces[font.family] = {
    file,
    upm: font.upm,
    winAscent: font.winAscent,
    winDescent: font.winDescent,
    ranges,
  };
}

const body = Object.entries(faces)
  .map(([family, data]) => `  ${JSON.stringify(family)}: ${JSON.stringify(data)},`)
  .join("\n");
writeFileSync(
  outFile,
  `// GENERATED by \`npm run fontmetrics\` from src-tauri/resources/fonts. Do not edit by hand:
// fontMetrics.conformance.test.ts fails when a font file and this table disagree.
import type { FaceData } from "./fontMetrics";

export const BUNDLED_FACES: Readonly<Record<string, FaceData>> = {
${body}
};
`,
);
console.log(`wrote ${path.relative(root, outFile)}: ${Object.keys(faces).join(", ")}`);
